apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: {{ .Values.app.name }}-build-test-push
  namespace: {{ .Values.app.namespace }}
  labels:
    {{- include "backstage.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/hook: Sync
spec:
  pipelineRef:
    name: {{ .Values.app.namespace }}-build-test-push
  params:
    - name: dockerfile
      value: {{ include "dockerfile.path" . }}
    - name: output-image
      value: {{ .Values.image.url }} # Example: quay.io/ch007m/my-quarkus-app"
    - name: url
      value: {{ include "git.repo.url" . }}
    - name: native
      value: {{ .Values.build.native }}
    - name: virtualMachineName
      value: {{ .Values.app.virtualMachineName }}
    - name: virtualMachineNamespace
      value: {{ .Values.app.virtualMachineNamespace }}
  workspaces:
    - name: project-dir
      persistentVolumeClaim:
        claimName: ${{ values.component_id }}-project-pvc
    - name: maven-m2-repo
      persistentVolumeClaim:
        claimName: ${{ values.component_id }}-m2-repo-pvc
    - name: maven-settings
      configMap:
        name: ${{ values.component_id }}-maven-settings
    - name: dockerconfig-ws
      secret:
        secretName: dockerconfig-secret
