apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- quarkus-dev-virtualmachine.yml

patches:
- patch: |
    - op: replace #action
      path: /spec/dataVolumeTemplates/0/spec/source/pvc/namespace #resource we want to change
      value: vm-images #value we want to use for e2e tests using github workflow
  target:
    group: kubevirt.io
    version: v1
    kind: VirtualMachine
    name: quarkus-dev
