{{- if not (eq .Values.environment "dev") -}}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: edit
  namespace: "{{ .Values.app.namespace }}"
subjects:
  - kind: ServiceAccount
    name: image-pusher
    namespace: {{ .Values.app.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
{{- end }}
